"""add password reset email time to users

Revision ID: 21df5503e778
Revises: fe4d7859b473
Create Date: 2026-10-03 20:22:08.616285

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21df5503e778"
down_revision: str | Sequence[str] | None = "fe4d7859b473"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password_reset_email_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_email_sent_at")
    # ### end Alembic commands ###
