"""add email verification to users

Revision ID: fe4d7859b473
Revises: 95119a855a83
Create Date: 2026-10-03 20:07:32.550228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe4d7859b473"
down_revision: str | Sequence[str] | None = "95119a855a83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Comptes existants : ceux reliés à Google sont vérifiés (Google garantit l'adresse) ; les
    autres restent non vérifiés et peuvent redemander l'email de vérification.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("verification_email_sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###
    op.execute(
        "UPDATE users SET email_verified_at = now() "
        "WHERE id IN (SELECT user_id FROM oauth_accounts)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verification_email_sent_at")
    op.drop_column("users", "email_verified_at")
    # ### end Alembic commands ###
